apiVersion: apps/v1
kind: Deployment
metadata:
  name: kenlabs-io-deployment
  labels:
    apptype: kenlabs-io
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: kenlabs-io
  template:
    metadata:
      labels:
        app: kenlabs-io
        apptype: kenlabs-io
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: kenlabs-io
          image: gitdatateam/kenlabs-io:{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
